name: build nix package
on:
  push:
    branches:
      - "main"
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      # checkout source code from github
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      # install nix package manager
      # https://github.com/cachix/install-nix-action
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # check if nix flakes is working
      - run: nix flake check

      # build package
      - name: nix build .#valorant-discord-bot
        run: |
          nix build .#valorant-discord-bot
